config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :departments
  resources :operators
  resources :categories
  resources :products
  resources :users
  resources :catalog, controller: 'categories', :only => [:index]

  root 'categories#catalog', as: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :operators
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_one :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  protect_from_forgery with: :exception

  protected
    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorize

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    flash[:notice] = "Category successfully created =)"
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(category_params)
    flash[:notice] = "Category was successfully updated =)"
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category was successfully deleted =)"
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
  end

  def catalog
    @categories = Category.where(params[:id])
  end

  private
    def category_params
      params.require(:category).permit(:title, :description, :product_ids => [])
    end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    Department.create(department_params)
    flash[:notice] = "Department successfully created =)"
    redirect_to departments_path
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    @department.update_attributes(department_params)
    flash[:notice] = "Department was successfully updated =)"
    redirect_to departments_path
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    flash[:notice] = "Department was successfully deleted =)"
    redirect_to departments_path
  end

  private
    def department_params
      params.require(:department).permit(:title, :description)
    end
    
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController

    def index
      @operators = Operator.all
    end

    def new
      @operator = Operator.new
    end

    def create
      Operator.create(operator_params)
      flash[:notice] = "Operator successfully created =)"
      redirect_to operators_path
    end

    def edit
      @operator = Operator.find(params[:id])
    end

    def update
      @operator = Operator.find(params[:id])
      @operator.update_attributes(operator_params)
      flash[:notice] = "Operator was successfully updated =)"
      redirect_to operators_path
    end

    def destroy
      @operator = Operator.find(params[:id])
      @operator.destroy
      flash[:notice] = "Operator was successfully deleted =)"
      redirect_to operators_path
    end

    private
      def operator_params
        params.require(:operator).permit(:name,:department_id)
      end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def create
      Product.create(product_params)
      flash[:notice] = "Product successfully created =)"
      redirect_to products_path
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      @product.update_attributes(product_params)
      flash[:notice] = "Product was successfully updated =)"
      redirect_to products_path
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      flash[:notice] = "Product was successfully deleted =)"
      redirect_to products_path
    end

    private
      def product_params
        params.require(:product).permit(:title, :image_url, :description, :price, :category_ids => [])
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize

  def index
    @users = User.order(:name)
    @operators = Operator.all
  end

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    flash[:notice] = "User account successfully created =)"
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    flash[:notice] = "User account was successfully updated =)"
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User was successfully deleted =)"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :operator_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Welcome Operator</h1>
<p>It's <%= Time.now %></p>

<p>Use the right navigation panel to access the administration controls</p>

app/views/categories/_form.html.erb
<%= link_to '< List of categories', categories_path %>

<div class="inner-form">
  <%= form_for @category do |f| %>
  <fieldset>
    <legend>Category information</legend>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control", :placeholder => "Category title" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, size: '60x6', :class => "form-control", :placeholder => "Category description" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save Category", :class => "btn btn-success"  %>
    </div>
  </fieldset>
  <% end %>
</div>

app/views/categories/catalog.html.erb
<h1>Product Catalog</h1>

<div align="right">
  Filter by category:
  <% @categories.each do |category| %>
    <%= link_to "#{category.title}", category, :class => "btn btn-info btn-sm" %>
  <% end %>
</div>

<% @categories.each do |category| %>
  <table class="table">
    <h2><%= category.title %></h2>
    <% category.products.each do |product| %>
      <div class="item">
        <div class="item-title"><%= product.title %></div>
        <div class="item-image"><%= image_tag(product.image_url) %></div>
        <div class="item-price"><%= number_to_currency(product.price) %></div>
      </div>
    <% end %>
  </table>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1>Categories List</h1>

<% @categories.each do |category| %>
  <h2><%= category.title %></h2>
  <table class="table">
    <tr>
      <td><%= category.description %></td>
      <td align="right">
        <%= link_to "edit", edit_category_path(category), :class => "btn btn-warning" %>
        <%= link_to "delete", category, method: :delete, :class => "btn btn-danger" %>
      </td>
    </tr>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Image</th>
        <th>Product</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% category.products.each do |product| %>
        <tr>
          <td class="attr-title"><%= product.title %></td>
          <td class="attr-image"><%= image_tag(product.image_url) %></td>
          <td class="attr-description"><%= product.description %></td>
          <td class="attr-price"><%= number_to_currency(product.price) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'new', new_category_path, :class => "btn btn-primary" %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h2>
<div class="back"><%= link_to '< All of categories', home_path %></div>

<table class="table">
  <% @category.products.each do |product| %>
    <div class="item">
      <div class="item-title"><%= product.title %></div>
      <div class="item-image"><%= image_tag(product.image_url) %></div>
      <div class="item-price"><%= number_to_currency(product.price) %></div>
    </div>
  <% end %>
</table>

app/views/departments/_form.html.erb
<%= link_to '< List of departments', categories_path %>

<div class="inner-form">
  <%= form_for @department do |f| %>
  <fieldset>
    <legend>Department information</legend>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control", :placeholder => "Department title" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, size: '60x6',
                      :class => "form-control",
                      :placeholder => "Department description" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save Department", :class => "btn btn-success" %>
    </div>
  <% end %>
  </fieldset>
</div>

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= render "form" %>

app/views/departments/index.html.erb
<h1>Departments List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td class="attr-title"><%= department.title %></td>
        <td class="attr-description"><%= department.description %></td>
        <td align="right">
          <%= link_to "edit", edit_department_path(department), :class => "btn btn-warning" %>
          <%= link_to 'delete', department, method: :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'new', new_department_path, :class => "btn btn-primary" %>

app/views/departments/new.html.erb
<h1>New Department</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Header row -->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <header>
          <div align="right" class="login">
            <% if session[:user_id] %>
              <%= link_to "Logout", logout_path, method: :delete, :class => "btn btn-default btn-sm" %>
            <% else %>
              <%= link_to "Log In", login_path, :class => "btn btn-success" %>
            <% end %>
          </div>
          <h1>Store App</h1>
          <h6>The best store of funs things!</h6>
        </header>
      </div>
    </div>

    <% if notice %>
      <div class="row">
        <div class="col-md-12">
          <p class="notice"><%= notice %></p>
        </div>
      </div>
    <% end %>

    <!-- Main row -->
    <div class="row">

      <% if session[:user_id] %>
        <div class="col-md-9 content">
          <%= yield %>
        </div>
        <div class="col-md-3 menu">
          <nav>
            <ul>
              <li><%= link_to "Home", home_path %></li>
              <li><%= link_to "Categories", categories_path %></li>
              <li><%= link_to "Products", products_path %></li>
              <li><%= link_to "Departments", departments_path %></li>
              <li><%= link_to "Operators", operators_path %></li>
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </nav>

        </div>
      <% else %>

        <div class="col-md-12 content">
          <%= yield %>
        </div>

      <% end %>
    </div>

    <!-- Footer row -->
    <div class="row">
      <footer class="col-md-12">
        Developed by Zarco at Codus.
      </footer>
    </div>

  </div>
  </body>

</html>

app/views/operators/_form.html.erb
<%= link_to '< List of operators', operators_path %>

<div class="inner-form">
  <%= form_for @operator do |f| %>
    <fieldset>
      <legend>Operator information</legend>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => "form-control", :placeholder => "Operator name" %>
      </div>
      <div class="form-group">
        <%= f.label :department %>
        <%= f.collection_select :department_id, Department.all, :id, :title, { :include_blank => "Select Operator's Department" }, { :class => "form-control" }  %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Operator", :class => "btn btn-success" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/operators/edit.html.erb
<h1>Edit Operator</h1>
<%= render "form" %>

app/views/operators/index.html.erb
<h1>Operator List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td class="attr-name"><%= operator.name %></td>
        <td class="attr-title"><%= Department.all.find(operator.department_id).title %></td>
        <td align="right">
          <%= link_to "edit", edit_operator_path(operator), :class => "btn btn-warning" %>
          <%= link_to 'delete', operator, method: :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'new', new_operator_path, :class => "btn btn-primary" %>

app/views/operators/new.html.erb
<h1>New Operator</h1>
<%= render "form" %>

app/views/products/_form.html.erb
<%= link_to '< List of products', categories_path %>

<div class="inner-form">
  <%= form_for @product do |f| %>
    <fieldset>
      <legend>Product information</legend>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, :class => "form-control", :placeholder => "Product title" %>
      </div>
      <div class="form-group">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, :class => "form-control", :placeholder => "Product image" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, size: '60x6', :class => "form-control", :placeholder => "Product description" %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, :class => "form-control", :placeholder => "Product price" %>
      </div>
      <div class="form-group">
        <%= f.label :category %>
        <%=f.select :category_ids, options_for_select(Category.all.collect {|c| [c.title, c.id] }, @product.category_ids ), {}, :multiple => true, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Product", :class => "btn btn-success" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render "form" %>

app/views/products/index.html.erb
<h1>Products List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="attr-title"><%= product.title %></td>
        <td class="attr-image"><%= image_tag(product.image_url) %></td>
        <td class="attr-description"><%= product.description %></td>
        <td class="attr-price"><%= number_to_currency(product.price) %></td>
        <td align="right">
          <%= link_to "edit", edit_product_path(product), :class => "btn btn-warning" %>
          <%= link_to "delete", product, method: :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'new', new_product_path, :class => "btn btn-primary" %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render "form" %>

app/views/users/_form.html.erb
<%= link_to '< List of users ', users_path %>

<div class="inner-form">
<%= form_for @user do |f| %>
  <fieldset>
    <legend>Account information</legend>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control", :placeholder => "Account name" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, size: 40, :class => "form-control", :placeholder => "Choose your password" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirm:' %>
      <%= f.password_field :password_confirmation, size: 40, :class => "form-control", :placeholder => "Repeat your password" %>
    </div>
    <div class="form-group">
      <%= f.label :operator %>
      <%= f.collection_select :operator_id, Operator.all, :id, :name, { :include_blank => "Select Operator User" }, { :class => "form-control" }  %>
    </div>
    <div class="form-group">
      <%= f.submit "Save User Account", :class => "btn btn-success" %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1>User List</h1>

<table class="table">
  <thead>
    <tr>
      <th>User-name</th>
      <th>Operator</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="attr-name"><%= user.name %></td>
        <td class="attr-operator"><%= @operators.find(user.operator_id).name %></td>
        <td align="right">
          <%= link_to "edit", edit_user_path(user), :class => "btn btn-warning" %>
          <%= link_to "delete", user, method: :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'new', new_user_path, :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form" %>